//Math => Librería de las Matemáticas.
var raiz_de_9 = Math.sqrt(81);
console.log(`Raíz de 81 => ${raiz_de_9}`);
console.log(`Numero Random entre 0 y 1 => ${Math.random()}`);
console.log(`Numero Random entre 30 y 60 con decimales=> ${Math.random() * (60-30) + 30}`);
console.log(`Numero Random entre 30 y 60 entero => ${parseInt(Math.random() * (60-30) + 30)}`);
console.log(`Piso de un número (ejm 4.9)=> ${Math.floor(4.9)}`);
console.log(`Techo de un número (ejm 4.1)=> ${Math.ceil(4.1)}`);
console.log(`Redondeo 3.6 => ${Math.round(3.6)}`);
console.log(`Redondeo 3.4 => ${Math.round(3.4)}`);
console.log(`Redondeo 3.5 => ${Math.round(3.5)}`);
console.log(`Redondeo 4.5 => ${Math.round(4.5)}`);
console.log(`Potencia de un numero => ${Math.pow(5,4)}`);
